//
// GeminiAskPostRequestFilesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GeminiAskPostRequestFilesInner: Codable, JSONEncodable, Hashable {

    public var fileName: String
    public var data: String

    public init(fileName: String, data: String) {
        self.fileName = fileName
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fileName
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fileName, forKey: .fileName)
        try container.encode(data, forKey: .data)
    }
}

