//
// GeminiAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class GeminiAPI {

    /**

     - parameter geminiAskPostRequest: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func geminiAskPost(geminiAskPostRequest: GeminiAskPostRequest? = nil, apiResponseQueue: DispatchQueue = RemoteTestToolsClientAPI.apiResponseQueue, completion: @escaping ((_ data: GeminiAskPost200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return geminiAskPostWithRequestBuilder(geminiAskPostRequest: geminiAskPostRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /gemini/ask
     - Execute a Gemini CLI command with the provided prompt
     - parameter geminiAskPostRequest: (body)  (optional)
     - returns: RequestBuilder<GeminiAskPost200Response> 
     */
    open class func geminiAskPostWithRequestBuilder(geminiAskPostRequest: GeminiAskPostRequest? = nil) -> RequestBuilder<GeminiAskPost200Response> {
        let localVariablePath = "/gemini/ask"
        let localVariableURLString = RemoteTestToolsClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: geminiAskPostRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GeminiAskPost200Response>.Type = RemoteTestToolsClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
