//
// HealthAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class HealthAPI {

    /**

     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func healthGet(apiResponseQueue: DispatchQueue = RemoteTestToolsClientAPI.apiResponseQueue, completion: @escaping ((_ data: HealthGet200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return healthGetWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /health
     - Health check endpoint
     - returns: RequestBuilder<HealthGet200Response> 
     */
    open class func healthGetWithRequestBuilder() -> RequestBuilder<HealthGet200Response> {
        let localVariablePath = "/health"
        let localVariableURLString = RemoteTestToolsClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<HealthGet200Response>.Type = RemoteTestToolsClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
