//
// GeminiAskPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GeminiAskPostRequest: Codable, JSONEncodable, Hashable {

    public var prompt: String?
    public var args: [String]?

    public init(prompt: String? = nil, args: [String]? = nil) {
        self.prompt = prompt
        self.args = args
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case prompt
        case args
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(prompt, forKey: .prompt)
        try container.encodeIfPresent(args, forKey: .args)
    }
}

