//
// GeminiAskPost200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GeminiAskPost200Response: Codable, JSONEncodable, Hashable {

    public var output: String?
    public var exitCode: Double?
    public var stderr: String?
    public var error: String?

    public init(output: String? = nil, exitCode: Double? = nil, stderr: String? = nil, error: String? = nil) {
        self.output = output
        self.exitCode = exitCode
        self.stderr = stderr
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case output
        case exitCode
        case stderr
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(output, forKey: .output)
        try container.encodeIfPresent(exitCode, forKey: .exitCode)
        try container.encodeIfPresent(stderr, forKey: .stderr)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

