//
// HealthGet200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HealthGet200Response: Codable, JSONEncodable, Hashable {

    public var status: String?
    public var timestamp: String?
    public var uptime: Double?

    public init(status: String? = nil, timestamp: String? = nil, uptime: Double? = nil) {
        self.status = status
        self.timestamp = timestamp
        self.uptime = uptime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case timestamp
        case uptime
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(uptime, forKey: .uptime)
    }
}

