name: Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: yarn lint

  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Run unit and integration tests
        run: yarn test

      - name: Build server
        run: yarn build

      - name: Set up Swift
        if: runner.os == 'macOS'
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.10"
      
      - name: Generate Swift Client
        if: runner.os == 'macOS'
        run: yarn generate:swift-client

      - name: Validate Swift Client is Up-to-Date
        if: runner.os == 'macOS'
        run: |
          if ! git diff --exit-code modules/swift-client/ modules/server/openapi.json; then
            echo "❌ Swift client is out of sync with server API!"
            echo "Please run 'yarn generate:swift-client' and commit the changes."
            exit 1
          fi
          echo "✅ Swift client is up-to-date"

      - name: Verify Swift Client Build
        if: runner.os == 'macOS'
        run: swift build